# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app_1012"
client_id = "7f348053d5f50dd2cc5951083507c3dd"
application_url = "https://ultram-harder-incomplete-civil.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://ultram-harder-incomplete-civil.trycloudflare.com/auth/callback",
  "https://ultram-harder-incomplete-civil.trycloudflare.com/auth/shopify/callback",
  "https://ultram-harder-incomplete-civil.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shopbytest.myshopify.com"
